# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import example_pb2 as example__pb2


class PbExampleServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.sendBatch = channel.unary_unary(
        '/PbExampleService/sendBatch',
        request_serializer=example__pb2.PbExampleDataRequest.SerializeToString,
        response_deserializer=example__pb2.PbExampleResponse.FromString,
        )
    self.compute = channel.unary_unary(
        '/PbExampleService/compute',
        request_serializer=example__pb2.PbExampleComputeRequest.SerializeToString,
        response_deserializer=example__pb2.PbExampleResponse.FromString,
        )


class PbExampleServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def sendBatch(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def compute(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PbExampleServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'sendBatch': grpc.unary_unary_rpc_method_handler(
          servicer.sendBatch,
          request_deserializer=example__pb2.PbExampleDataRequest.FromString,
          response_serializer=example__pb2.PbExampleResponse.SerializeToString,
      ),
      'compute': grpc.unary_unary_rpc_method_handler(
          servicer.compute,
          request_deserializer=example__pb2.PbExampleComputeRequest.FromString,
          response_serializer=example__pb2.PbExampleResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'PbExampleService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
