# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modelalgo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modelalgo.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\n!com.spark.dialect.generated.protoB\016ModelAlgorithmH\001\210\001\001\240\001\001'),
  serialized_pb=_b('\n\x0fmodelalgo.proto\"a\n\x19ModelAlgorithmDataRequest\x12\x0e\n\x06taskId\x18\x01 \x01(\t\x12\x0e\n\x06schema\x18\x02 \x01(\t\x12\x11\n\tbatchSize\x18\x03 \x01(\x03\x12\x11\n\tbatchData\x18\x04 \x01(\x0c\"B\n\x1cModelAlgorithmComputeRequest\x12\x0e\n\x06taskId\x18\x01 \x01(\t\x12\x12\n\ntargetFile\x18\x02 \x01(\t\",\n\x1aModelAlgorithmCleanRequest\x12\x0e\n\x06taskId\x18\x01 \x01(\t\"C\n\x1cModelAlgorithmPredictRequest\x12\x11\n\tmodelFile\x18\x01 \x01(\t\x12\x10\n\x08\x66\x65\x61tures\x18\x02 \x01(\x0c\"\x80\x01\n\x16ModelAlgorithmResponse\x12.\n\x06status\x18\x01 \x01(\x0e\x32\x1e.ModelAlgorithmResponse.STATUS\x12\x0f\n\x07message\x18\x02 \x01(\t\"%\n\x06STATUS\x12\x06\n\x02OK\x10\x00\x12\x08\n\x04\x42USY\x10\x01\x12\t\n\x05\x45RROR\x10\x02\"{\n\x14ModelPredictResponse\x12,\n\x06status\x18\x01 \x01(\x0e\x32\x1c.ModelPredictResponse.STATUS\x12\x0e\n\x06result\x18\x02 \x01(\x0c\"%\n\x06STATUS\x12\x06\n\x02OK\x10\x00\x12\x08\n\x04\x42USY\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x32\xa3\x02\n\x15ModelAlgorithmService\x12@\n\tsendBatch\x12\x1a.ModelAlgorithmDataRequest\x1a\x17.ModelAlgorithmResponse\x12\x43\n\tcomputeLR\x12\x1d.ModelAlgorithmComputeRequest\x1a\x17.ModelAlgorithmResponse\x12\x42\n\ncleanBatch\x12\x1b.ModelAlgorithmCleanRequest\x1a\x17.ModelAlgorithmResponse\x12?\n\x07predict\x12\x1d.ModelAlgorithmPredictRequest\x1a\x15.ModelPredictResponseB;\n!com.spark.dialect.generated.protoB\x0eModelAlgorithmH\x01\x88\x01\x01\xa0\x01\x01\x62\x06proto3')
)



_MODELALGORITHMRESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='STATUS',
  full_name='ModelAlgorithmResponse.STATUS',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BUSY', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=393,
  serialized_end=430,
)
_sym_db.RegisterEnumDescriptor(_MODELALGORITHMRESPONSE_STATUS)

_MODELPREDICTRESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='STATUS',
  full_name='ModelPredictResponse.STATUS',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BUSY', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=393,
  serialized_end=430,
)
_sym_db.RegisterEnumDescriptor(_MODELPREDICTRESPONSE_STATUS)


_MODELALGORITHMDATAREQUEST = _descriptor.Descriptor(
  name='ModelAlgorithmDataRequest',
  full_name='ModelAlgorithmDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='taskId', full_name='ModelAlgorithmDataRequest.taskId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='schema', full_name='ModelAlgorithmDataRequest.schema', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='batchSize', full_name='ModelAlgorithmDataRequest.batchSize', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='batchData', full_name='ModelAlgorithmDataRequest.batchData', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=116,
)


_MODELALGORITHMCOMPUTEREQUEST = _descriptor.Descriptor(
  name='ModelAlgorithmComputeRequest',
  full_name='ModelAlgorithmComputeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='taskId', full_name='ModelAlgorithmComputeRequest.taskId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='targetFile', full_name='ModelAlgorithmComputeRequest.targetFile', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=184,
)


_MODELALGORITHMCLEANREQUEST = _descriptor.Descriptor(
  name='ModelAlgorithmCleanRequest',
  full_name='ModelAlgorithmCleanRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='taskId', full_name='ModelAlgorithmCleanRequest.taskId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=230,
)


_MODELALGORITHMPREDICTREQUEST = _descriptor.Descriptor(
  name='ModelAlgorithmPredictRequest',
  full_name='ModelAlgorithmPredictRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='modelFile', full_name='ModelAlgorithmPredictRequest.modelFile', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='features', full_name='ModelAlgorithmPredictRequest.features', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=232,
  serialized_end=299,
)


_MODELALGORITHMRESPONSE = _descriptor.Descriptor(
  name='ModelAlgorithmResponse',
  full_name='ModelAlgorithmResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='ModelAlgorithmResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='ModelAlgorithmResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MODELALGORITHMRESPONSE_STATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=302,
  serialized_end=430,
)


_MODELPREDICTRESPONSE = _descriptor.Descriptor(
  name='ModelPredictResponse',
  full_name='ModelPredictResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='ModelPredictResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result', full_name='ModelPredictResponse.result', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MODELPREDICTRESPONSE_STATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=432,
  serialized_end=555,
)

_MODELALGORITHMRESPONSE.fields_by_name['status'].enum_type = _MODELALGORITHMRESPONSE_STATUS
_MODELALGORITHMRESPONSE_STATUS.containing_type = _MODELALGORITHMRESPONSE
_MODELPREDICTRESPONSE.fields_by_name['status'].enum_type = _MODELPREDICTRESPONSE_STATUS
_MODELPREDICTRESPONSE_STATUS.containing_type = _MODELPREDICTRESPONSE
DESCRIPTOR.message_types_by_name['ModelAlgorithmDataRequest'] = _MODELALGORITHMDATAREQUEST
DESCRIPTOR.message_types_by_name['ModelAlgorithmComputeRequest'] = _MODELALGORITHMCOMPUTEREQUEST
DESCRIPTOR.message_types_by_name['ModelAlgorithmCleanRequest'] = _MODELALGORITHMCLEANREQUEST
DESCRIPTOR.message_types_by_name['ModelAlgorithmPredictRequest'] = _MODELALGORITHMPREDICTREQUEST
DESCRIPTOR.message_types_by_name['ModelAlgorithmResponse'] = _MODELALGORITHMRESPONSE
DESCRIPTOR.message_types_by_name['ModelPredictResponse'] = _MODELPREDICTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ModelAlgorithmDataRequest = _reflection.GeneratedProtocolMessageType('ModelAlgorithmDataRequest', (_message.Message,), {
  'DESCRIPTOR' : _MODELALGORITHMDATAREQUEST,
  '__module__' : 'modelalgo_pb2'
  # @@protoc_insertion_point(class_scope:ModelAlgorithmDataRequest)
  })
_sym_db.RegisterMessage(ModelAlgorithmDataRequest)

ModelAlgorithmComputeRequest = _reflection.GeneratedProtocolMessageType('ModelAlgorithmComputeRequest', (_message.Message,), {
  'DESCRIPTOR' : _MODELALGORITHMCOMPUTEREQUEST,
  '__module__' : 'modelalgo_pb2'
  # @@protoc_insertion_point(class_scope:ModelAlgorithmComputeRequest)
  })
_sym_db.RegisterMessage(ModelAlgorithmComputeRequest)

ModelAlgorithmCleanRequest = _reflection.GeneratedProtocolMessageType('ModelAlgorithmCleanRequest', (_message.Message,), {
  'DESCRIPTOR' : _MODELALGORITHMCLEANREQUEST,
  '__module__' : 'modelalgo_pb2'
  # @@protoc_insertion_point(class_scope:ModelAlgorithmCleanRequest)
  })
_sym_db.RegisterMessage(ModelAlgorithmCleanRequest)

ModelAlgorithmPredictRequest = _reflection.GeneratedProtocolMessageType('ModelAlgorithmPredictRequest', (_message.Message,), {
  'DESCRIPTOR' : _MODELALGORITHMPREDICTREQUEST,
  '__module__' : 'modelalgo_pb2'
  # @@protoc_insertion_point(class_scope:ModelAlgorithmPredictRequest)
  })
_sym_db.RegisterMessage(ModelAlgorithmPredictRequest)

ModelAlgorithmResponse = _reflection.GeneratedProtocolMessageType('ModelAlgorithmResponse', (_message.Message,), {
  'DESCRIPTOR' : _MODELALGORITHMRESPONSE,
  '__module__' : 'modelalgo_pb2'
  # @@protoc_insertion_point(class_scope:ModelAlgorithmResponse)
  })
_sym_db.RegisterMessage(ModelAlgorithmResponse)

ModelPredictResponse = _reflection.GeneratedProtocolMessageType('ModelPredictResponse', (_message.Message,), {
  'DESCRIPTOR' : _MODELPREDICTRESPONSE,
  '__module__' : 'modelalgo_pb2'
  # @@protoc_insertion_point(class_scope:ModelPredictResponse)
  })
_sym_db.RegisterMessage(ModelPredictResponse)


DESCRIPTOR._options = None

_MODELALGORITHMSERVICE = _descriptor.ServiceDescriptor(
  name='ModelAlgorithmService',
  full_name='ModelAlgorithmService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=558,
  serialized_end=849,
  methods=[
  _descriptor.MethodDescriptor(
    name='sendBatch',
    full_name='ModelAlgorithmService.sendBatch',
    index=0,
    containing_service=None,
    input_type=_MODELALGORITHMDATAREQUEST,
    output_type=_MODELALGORITHMRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='computeLR',
    full_name='ModelAlgorithmService.computeLR',
    index=1,
    containing_service=None,
    input_type=_MODELALGORITHMCOMPUTEREQUEST,
    output_type=_MODELALGORITHMRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='cleanBatch',
    full_name='ModelAlgorithmService.cleanBatch',
    index=2,
    containing_service=None,
    input_type=_MODELALGORITHMCLEANREQUEST,
    output_type=_MODELALGORITHMRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='predict',
    full_name='ModelAlgorithmService.predict',
    index=3,
    containing_service=None,
    input_type=_MODELALGORITHMPREDICTREQUEST,
    output_type=_MODELPREDICTRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MODELALGORITHMSERVICE)

DESCRIPTOR.services_by_name['ModelAlgorithmService'] = _MODELALGORITHMSERVICE

# @@protoc_insertion_point(module_scope)
